version: '3.9'
services:
  frontend:
    build: 
      context: .
      dockerfile: ./infra/frontend/Dockerfile
    container_name: ${APP_NAME}_frontend
    working_dir: '/root/src'
    tty: true
    volumes:
      - ./src/frontend:/root/src
    ports:
      - 3333:3000
    environment:
      - WATCHPACK_POLLING=true
  backend:
    build: 
      context: .
      dockerfile: ./infra/backend/Dockerfile
    container_name: ${APP_NAME}_backend
    working_dir: '/root/src'
    tty: true
    volumes:
      - ./src/backend:/root/src
    ports:
      - 8888:80
  db:
    container_name: ${APP_NAME}_db
    build:
      context: .
      dockerfile: ./infra/db/Dockerfile
      args:
        - MYSQL_DATABASE=${DB_NAME}
        - MYSQL_USER=${DB_USER}
        - MYSQL_PASSWORD=${DB_PASS}
        - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    ports:
      - 3336:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
volumes:
  db-store: